# Generated by Django 6.0 on 2025-12-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Main question text or description of the kanji.')),
                ('kanji', models.CharField(blank=True, help_text='Optional kanji being tested.', max_length=16)),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('category', models.CharField(blank=True, help_text='Optional category/tag (e.g., JLPT level, topic).', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.SlugField(help_text='Short code identifier (e.g. skip_plus2).', max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('effect_type', models.CharField(choices=[('move_extra', 'Move extra cells'), ('heal', 'Heal HP'), ('shield', 'Damage shield'), ('reroll', 'Reroll dice'), ('swap_position', 'Swap position with another player'), ('change_question', 'Change question'), ('custom', 'Custom effect')], default='custom', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict, help_text="Config for the effect (e.g., {'cells': 2, 'max_hp_gain': 1}).")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code to join the game (e.g. ABC123).', max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=16)),
                ('mode', models.CharField(choices=[('finish', 'Finish Line'), ('survival', 'Survival')], default='finish', max_length=16)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('board_length', models.PositiveSmallIntegerField(default=40, help_text='Number of tiles on the board (including start/finish).')),
                ('current_turn_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_order', models.PositiveSmallIntegerField(help_text='Order of turns within the game (0-based).')),
                ('hp', models.PositiveSmallIntegerField(default=3)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('eliminated_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game', 'turn_order'],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_game', 'Create Game'), ('join_game', 'Join Game'), ('start_game', 'Start Game'), ('roll_dice', 'Roll Dice'), ('move', 'Move'), ('tile_effect', 'Tile Effect'), ('question_start', 'Question Start'), ('question_answer', 'Question Answer'), ('duel_start', 'Duel Start'), ('duel_result', 'Duel Result'), ('card_use', 'Use Card'), ('player_eliminated', 'Player Eliminated'), ('game_end', 'Game End')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw event data (dice value, old/new positions, question id, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='game.playeringame')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='game.playeringame'),
        ),
        migrations.CreateModel(
            name='SupportCardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.playeringame')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='game.supportcardtype')),
            ],
            options={
                'ordering': ['owner', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Zero-based index from start (0) to last tile.')),
                ('tile_type', models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('question', 'Question'), ('trap', 'Trap'), ('heal', 'Heal'), ('bonus', 'Bonus'), ('warp', 'Warp'), ('mass_warp', 'Mass Warp'), ('duel', 'Duel'), ('shop', 'Shop'), ('empty', 'Empty')], default='empty', max_length=32)),
                ('label', models.CharField(blank=True, help_text='Short label to show on the board (optional).', max_length=64)),
                ('value_int', models.IntegerField(blank=True, help_text='Optional numeric value (e.g., +HP, -coins, warp steps).', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Optional JSON config for custom tile effects.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='game.game')),
            ],
            options={
                'ordering': ['game', 'position'],
                'unique_together': {('game', 'position')},
            },
        ),
    ]
