# Generated by Django 6.0 on 2025-12-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtile',
            name='value_int',
            field=models.IntegerField(blank=True, help_text='Optional numeric value (HP change, coin change, move steps, warp index, etc.).', null=True),
        ),
    ]
