# Generated by Django 5.2.7 on 2025-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_boardtile_value_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enabled_tiles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='pending_question',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='extra_rolls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extra dice rolls available (from Reroll Dice card).'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='shield_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='Blocks incoming damage (negative HP deltas) until depleted.'),
        ),
        migrations.AlterField(
            model_name='boardtile',
            name='tile_type',
            field=models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('question', 'Question'), ('trap', 'Trap'), ('heal', 'Heal'), ('bonus', 'Bonus'), ('warp', 'Warp'), ('mass_warp', 'Mass Warp'), ('duel', 'Duel'), ('shop', 'Shop'), ('safe', 'Safe')], default='safe', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='board_length',
            field=models.PositiveSmallIntegerField(default=50, help_text='Number of tiles on the board (including start/finish).'),
        ),
        migrations.AlterField(
            model_name='supportcardtype',
            name='effect_type',
            field=models.CharField(choices=[('move_extra', 'Move extra cells'), ('heal', 'Heal HP'), ('shield', 'Damage shield'), ('reroll', 'Reroll dice'), ('swap_position', 'Swap position with another player'), ('change_question', 'Change question'), ('custom', 'Custom effect'), ('bonus_coin', 'Bonus coin')], default='custom', max_length=32),
        ),
    ]
