# Generated by Django 6.0 on 2025-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_boardtile_tile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='draft_options',
            field=models.JSONField(blank=True, default=list, help_text='Current draft option card_type IDs offered to this player (Draft Mode only).'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='draft_picks',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many draft picks this player has completed (Draft Mode only).'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('finish', 'Finish Line'), ('draft', 'Draft Mode'), ('survival', 'Survival')], default='finish', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players'), ('drafting', 'Drafting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=16),
        ),
    ]
