# Generated by Django 6.0 on 2026-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_pending_gun_alter_boardtile_tile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ordering_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players'), ('ordering', 'Rolling for turn order'), ('drafting', 'Drafting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=16),
        ),
    ]
