# Generated by Django 4.2.17 on 2026-01-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_boardtile_id_alter_game_board_length_and_more'),
        ('game', '0010_game_ordering_state_alter_game_status'),
        ('game', '0010_gamechatmessage'),
    ]

    operations = [
    ]
