# Generated by Django 6.0 on 2026-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_boardtile_id_alter_game_board_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDuelCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('plus_status', '+ Status'), ('minus_status', '- Status'), ('neutral', 'Neutral'), ('bonus', 'Bonus')], db_index=True, default='neutral', max_length=20)),
                ('effect_type', models.CharField(choices=[('damage', 'Damage'), ('heal', 'Heal'), ('shield', 'Shield'), ('draw', 'Draw'), ('apply_status', 'Apply Status'), ('cleanse', 'Cleanse'), ('remove_enemy_shield', 'Remove Enemy Shield')], default='damage', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_deck',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_discard',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_hand',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_turn_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('finish', 'Custom Game'), ('draft', 'Draft Mode'), ('survival', 'Survival'), ('card_duel', 'Card Duel')], default='finish', max_length=16),
        ),
    ]
