# Generated by Django 6.0 on 2026-01-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_cardduelcardtype_playeringame_cd_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='cd_pick_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='cd_picks_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
