# Generated by Django 6.0 on 2026-01-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_profile'),
        ('game', '0014_playeringame_cd_pick_options_and_more'),
    ]

    operations = [
    ]
