# Generated by Django 5.2.7 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_merge_20260130_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='finish_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order in which this player crossed the finish line (1=first, 2=second, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='cardduelcardtype',
            name='effect_type',
            field=models.CharField(choices=[('damage', 'Damage'), ('heal', 'Heal'), ('shield', 'Shield'), ('draw', 'Draw'), ('apply_status', 'Apply Status'), ('cleanse', 'Cleanse'), ('remove_enemy_shield', 'Remove Enemy Shield'), ('swap_shield', 'Swap Shield'), ('heal_and_shield', 'Heal + Shield'), ('discard_and_draw', 'Discard & Draw'), ('gamble', 'Gamble'), ('antidote', 'Antidote')], default='damage', max_length=32),
        ),
    ]
