# Generated by Django 5.2.7 on 2026-02-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_playeringame_finish_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, requires password to join.'),
        ),
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password for private games.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='guest_session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
