# Generated by Django 4.2.17 on 2026-02-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0017_game_is_private_game_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='game',
            name='password',
        ),
        migrations.RemoveField(
            model_name='playeringame',
            name='guest_session_key',
        ),
        migrations.RemoveField(
            model_name='playeringame',
            name='player_name',
        ),
        migrations.AlterField(
            model_name='playeringame',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
